#!/bin/sh

echo "Content-Type:text/html"
echo ""
echo ""
#echo $QUERY_STRING
	ssid=`echo $QUERY_STRING | cut -d'&' -f 1 | cut -d'=' -f 2`
	passwd=`echo $QUERY_STRING | cut -d'&' -f 2 | cut -d'=' -f 2`
  	enc=`echo $QUERY_STRING | cut -d'&' -f 3 | cut -d'=' -f 2`
	channel=`echo $QUERY_STRING | cut -d'&' -f 4 | cut -d'=' -f 2`
  uci set wireless.@wifi-iface[0].ssid=$ssid
  uci set wireless.@wifi-iface[0].encryption=$enc
  uci set wireless.@wifi-iface[0].key=$passwd
  uci set wireless.wifi0.channel=$channel
  uci set wireless.@wifi-iface[0].network=wwan
  uci set wireless.@wifi-iface[0].mode=sta
  uci commit wireless
  
  uci set network.wwan=interface
  uci set network.wwan.proto=dhcp
  uci set network.lan.ipaddr=192.168.2.1
  uci commit network
  uci set firewall.@defaults[0].forward=ACCEPT
  uci commit firewall

  
  #echo "$ssid"
  #echo "<br />"
  #echo "$passwd"
  #echo "<br />"
  #echo "$enc"
  #echo "<br />"
echo  "Set STA OK!<br />"
  /etc/init.d/network restart

