#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

SERVICE_USE_PID=1
SERVICE_DAEMONIZE=1

START=99

start() {
        service_start /bin/shellguid
	/usr/shellgui/progs/main.sbin init
	/usr/shellgui/progs/main.sbin h_ji
}

stop() {
        service_stop /bin/shellguid
}
